### PR TITLE
Link to the new BroccoliPlugins.com

### PR DESCRIPTION
**Pull request by pootsbook**
Thanks to @gcollazo (EmberAddons) and @Kerry350.

### CODE REVIEW

**Comment by folz** [comment]
Screenshot of broccoliplugins.com

Looks like there's nothing there?

**Comment by pootsbook** [comment]
@folz possibly a DNS propagation issue? Where are you based?

Actually, www isn't configured, I'll add that.

**Comment by pootsbook** [comment]
DNS was fine, Heroku wasn't configured to recognise www. Thanks for catching that, fixed:

broccoli plugins 2015-02-11 14-29-56

**Comment by folz** [comment]
sweet, thanks!

**Comment by pootsbook** [comment]
:+1: you're welcome. Nice site :smile:

**Pull request merged**
